### ISSUE TITLE
windows.h

### ISSUE THREAD

**Issue by filisdiez** [tavrez/openssh-sk-winhello#10]
Hello! I want to install your project on wsl2, but when you start make, I get a message that fatal error: windows.h: No such file or directory if other errors appear. Please tell me, maybe something needs to be established before making such mistakes?

**Comment by tavrez** [comment]
WSL does not have access to Windows Hello, you need to configure your OpenSSH in wsl to use a ssh-sk-helper in windows(which means you have to install something like gitforwindows, or just copy the ssh-sk-helper from it to your windows). Also, you do not need to compile by yourself, binaries are provided in the release. Check [WSL.md](https://github.com/tavrez/openssh-sk-winhello/blob/master/WSL.md) for more info
