### ISSUE TITLE
Query regarding non-admin functionality

### ISSUE THREAD

**Issue by gettheguru** [tavrez/openssh-sk-winhello#2]
Hello,

First and foremost - thank you for releasing this interesting project to the open source community.

I understand through reading your project that you can interact with the FIDO/U2F keys without Administrator privileges by using the Windows Hello API. 

Can you confirm for me whether you can use this project entirely without Administrator rights? e.g. not running Git for Windows as Administrator. 

Can you also let me know if there is any implementation option using this using WSL2? I understand Git for Windows uses POSIX which is being deprecated.

My goal is to be able to enable FIDO/U2F (or PIV Smart Card) authentication from Windows 10 Enterprise hosts to Linux systems. Unfortunately the OpenSSH implementation in Powershell is woefully out of date.

**Comment by tavrez** [comment]
Hello,
Sorry for late answer.
About administrator privileges, yes you can use this without any administrator privileges, this project use implementation is same  as browsers like firefox and chrome.
About WSL, I know fido keys are not working in WSL1, I'm not sure about WSL2

**Comment by tavrez** [comment]
@gettheguru If you are still interested in using this project inside WSL(both 1&2), I've added brief description in [WSL](./WSL.md).
