### ISSUE TITLE
Error during keygen

### ISSUE THREAD

**Issue by TheCreeperCow** [tavrez/openssh-sk-winhello#3]
Goodday when i try to generate a key it gives the following error. but it does make the keys however i have the feeling those keys are not bound to my U2F key here is the information about the error and the command i used

Error: `WinHello API Error: Version=2, Is user available=0, user=0`

Command: `ssh-keygen -t ecdsa-sk -w /etc/winhello.dll -O user=Lars`

Note: user Lars exist on the windows system

**Comment by tavrez** [comment]
Are you using the latest version(v1.0.1)?

**Comment by TheCreeperCow** [comment]
Yes
